### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by ChShersh** [kowainik/hit-on#34]
README with usage examples for every command

**Comment by vrom911** [comment]
Hey @Jigar3! Thanks for the interest in the project :blush: 
I guess if you're learning Haskell it would be more interesting for you to do some Haskell-related issues rather than the documentation one. If you also feel so, you can check out #39; it could be useful for learning something new! Feel free to ask any questions and let me know what you think about this :slightly_smiling_face:

**Comment by Jigar3** [comment]
Sure thing. I was thinking if I would start with documentation then I could get a chance to get to know the codebase better and then I could delve deeper into actual coding.

**Comment by ChShersh** [comment]
@Jigar3 This project was created only yesterday and there's almost no documentation at all :slightly_smiling_face: @vrom911 and I have plans to write extensive documentation for everything quickly, so people can start using this tool ASAP. I think further improvements can be done later when something is not completely clear. I think, if you want to contribute you can start with #39 and ask questions if any :slightly_smiling_face:
