### ISSUE TITLE
`hit fix` - make commit and push

### ISSUE THREAD

**Issue by vrom911** [kowainik/hit-on#39]
At the moment we have `hit fix` command which amends the changes to the latest commit and force pushes the branch. I guess the better name for this command is `hit amend`.

I can see the better usage for the `hit fix` command: to make the separate commit (without the issue prefix) and to push the branch.

So, to resolve this issue ones need:

- [x]  Rename `hit fix` to `hit amend`
- [x]  Implement `hit fix` command which will take the optional string as the commit message (if the optional string is not provided then use "Fix after review" message), make the commit to the current branch and push the current branch.

**Comment by ChShersh** [comment]
@Jigar3 hi! I wonder, do you still have plans on finish this issue? Otherwise we would like to proceed with it and finish soon :slightly_smiling_face:

**Comment by Jigar3** [comment]
I have started working on it. Will submit a PR soon. 😀

**Comment by Jigar3** [comment]
```
runFix :: Maybe Text -> IO ()
runFix = \case
    Nothing -> do
        "git" ["add", "."]
        "git" ["commit", "-m", "Fix after review"]
        runPush False
    Just msg -> do
        "git" ["add", "."]
        "git" ["commit", "-m "] ++ msg
        runPush False
```
```
Error:

• Couldn't match expected type ‘[a1]’ with actual type ‘Text’
• In the second argument of ‘(++)’, namely ‘msg’
```

I am getting this error and am not sure if its the correct approach. Could you guide me please :sweat_smile:

**Comment by ChShersh** [comment]
@Jigar3 The problem is in this line:

```
"git" ["commit", "-m "] ++ msg
```

You want to append `msg` to the list `["commit", "-m "]` but instead you're appending it to function call `"git" ["commit", "-m "]`. What you want is something like:

```haskell
"git" $ ["commit", "-m "] ++ [msg]
```

Or just

```haskell
"git" ["commit", "-m ", msg]
```

Also you may notice some code duplication in your function. Instead of pattern-matching on `Maybe` on top level you can just construct message text from that `Maybe Text` and pass it to `"git"` inside list. I hope that helps!
